# Generated by Django 5.1.1 on 2024-09-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='thread_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
